package May_25th_Class_While_Loop;

public class Lab_123_While4 {
    public static void main(String[] args) {
        while (true){
            System.out.println("Hello, Pramod");     //infinite output
        }

    }
}
//output
// Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//Hello, Pramod
//
//Process finished with exit code 130
